### ISSUE TITLE
Compendium of Forgotten Secrets Tracker

### ISSUE THREAD

**Issue by ColdAnkles** [aurorabuilder/elements#249]
~~#248 adds starting files for COFSA Additions. This issue is to be used to track who's adding what.~~
~~#262 added first content batch~~
Thanks for everyone's help with Part 1 - all merged and available.
#309 adds more content.

If you want to help, grab the compendium from https://www.genfantasypress.com/about-the-compendium and reply with what you're working on.

- Warlock Patrons
  - [x] Accursed Archive (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Ashen Wolf (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Blackthorn Grove (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Currency Conspiracy (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Eternal Citadel (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Fallen Exile (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Forbidden Graveyard (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Gelatinous Convocation (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Gray Portrait (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Keeper of the Depths (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Perfect Chord (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Serpent Empress (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Shadowcat (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Storm Lord (Cold_Ankles)
    - [x] Invocations (LordSionnach)
  - [x] Warrior-Saint (Kektagon)
    - [x] Invocations (Kektagon)
  - [x] Weaver of Lies (Kektagon)
    - [x] Invocations (Kektagon)
  - [x] Wild Huntsman (J75057exe)
    - [x] Invocations
  
- Other Archetypes
  - Barbarian
    - [x] Path of the Accursed (Azzzzzy)
    - [x] Path of the Mercurial (Cold_Ankles)
  - Bard
    - [x] College of Harbingers (Azzzzzy)
    - [x] College of Portraiture (LordSionnach)
  - Fighter
    - [x] Timeless Monumental
    - [x] Discordant
  - Monk
    - [x] Way of the Black Star (Azzzzzy)
    - [x] Way of the Noble Serpent (Azzzzzy)
  - Paladin
    - [x] Oath of Avarice (LordSionnach)
    - [x] Oath of Judgement
  - Ranger
    - [x] Hound of the Huntsman
  - Rogue
    - [x] Graverobber
    - [x] Spidertouched
  - Sorcerer
    - [x] Ashen Lineage (Azzzzzy)
    - [x] Blackthorn Lineage (Azzzzzy)
  - Wizard
    - [x] Esoteric Plasmology (Azzzzy)
    - [x] Dream Cartography (LordSionnach)

- [x] Spells (Azzzzzy)
- [x] Familiars (To be done after companion part of Aurora updated)
- [x] Races (Azzzzy)
- [x] Feats (LordSionnach)

**Comment by Azzzzzy** [comment]
I can start working on the Spells

**Comment by ColdAnkles** [comment]
For IDs i've been using ID_GENP_COFSA_ where PHB has ID_WOTC_PHB_ and ID_COFSA_ where PHB has ID_PHB_

The only new spell explicitly referenced in The Fallen Exile is Falling star - which I gave ID_COFSA_SPELL_FALLING_STAR

**Comment by swdriessen** [comment]
You can use **`ID_GFP_COFSA_`** everywhere for consistency.
Some old IDs don't include wotc/phb because they are from the very first implementations and changing IDs now breaks character files or custom content when people override things or reference the IDs.

**Comment by Azzzzzy** [comment]
Working on Ashen Lineage Sorcerous Origin

**Comment by Azzzzzy** [comment]
Working on Blackthorn Lineage Sorcerous Origin

**Comment by swdriessen** [comment]
index merged, individual pull requests can be made

**Comment by Azzzzzy** [comment]
Working on Alfallen Race (Might take some time)

**Comment by shanebirley** [comment]
I just added some spells. Would appreciate anyone taking a peek and letting me know if I did it correctly. I *think* I did but not entirely convinced yet.

**Comment by ColdAnkles** [comment]
Another Warlock Patron completed today (Currency Conspiracy)

**Comment by ColdAnkles** [comment]
Forbidden Graveyard added to the second Pull Request

**Comment by Kektagon** [comment]
So I'm in love with the Compendium, so I thought that I'd contribute. Here's the Warrior Saint and the Weaver of Lies. Also their invocations. 


[Patrons and Invocations.zip](https://github.com/aurorabuilder/elements/files/3233576/Patrons.and.Invocations.zip)

**Comment by LordSionnach** [comment]
Made an account specifically so I could help with this. I have next to no experience coding, but thanks to Kektagon I understand how to do the invocations for the patrons, if not how to make the patrons.

I got several done in a productive moment (All the Gray Portrait, Accursed Archive, Ashen Wolf, and Bloodthorn Grove), and will upload them here once I have a bit of sleep and put the invocations into an actual order, rather than just starting after Kektagon's code.

Again, I'm new so sorry if you don't want me using  Kektagon's code to work off of.

**Comment by J75057exe** [comment]
I'm really enjoying the builder so I'd like to give back a bit. I'm up for coding in the Wild Huntsman Patron

**Comment by J75057exe** [comment]
I've done the wild huntsman file now.
ill do the associated invocations now

**Comment by LordSionnach** [comment]
> Edit: I'm new to GitHub, how do I upload the file?

As far as I can see, the bottom of the text box.

**Comment by ColdAnkles** [comment]
@LordSionnach Thank you very muchly for your contribution - I've added it to the pull request after a brief review. Will go over it again at some point if nobody else does.

@J75057exe You can add the completed file(s) to the reply and I'll add them in myself, or you can commit directly into my pull request - though I don't know how to do that myself...

**Comment by LordSionnach** [comment]
I've also just noticed that Compendium adds in a ton of invocations that don't have to do with any specific patron on page 106 of the free pdf. I'm going to add those to the invocation file as well.  (They also made a bunch of feats, but I have no idea how to do those. I'll see what I can do tho)

**Comment by LordSionnach** [comment]
And since I had nothing to do at 3am, here's the Bard's College of Portraiture. I was a little confused about one of the features though, specifically the line "You gain proficiency in any tools required to paint or create statuary". 

It sounded like they gained proficiency in mason's tools, potter's tools, woodcarver's tools, and painter's tools since all those can technically be used to paint/make statues, but I went with just mason's tools and painter's tools in the end since I think that's what it actually means. Let me know if I made a good assumption, or if I should add the others in.
[bard-portraiture.zip](https://github.com/aurorabuilder/elements/files/3434734/bard-portraiture.zip)

**Comment by LordSionnach** [comment]
Here are the feats!
[feats.zip](https://github.com/aurorabuilder/elements/files/3437481/feats.zip)

**Comment by LordSionnach** [comment]
And here's the Paladin archetype Oath of Avarice. Was easier to do than I thought it might be.
[paladin-avarice.zip](https://github.com/aurorabuilder/elements/files/3437880/paladin-avarice.zip)

**Comment by Rieleniel** [comment]
Is anyone doing Hound of The Huntsman, the Ranger archetype? I can't see it anywhere here.

**Comment by ColdAnkles** [comment]
I'd somehow managed to miss it - good catch. Nobody's working on it to my knowledge.

**Comment by Rieleniel** [comment]
I've finished it, let's say, but I can't get through the AC part. I've made
a quick fix, but if you can help me understand how AC works in Aurora, I
can finish that, too, I think.

Cold_Ankles <notifications@github.com> ezt írta (időpont: 2019. aug. 15.,
Csü 13:29):

**Comment by ColdAnkles** [comment]
Assuming you mean in the "Winter's Might" feature, which allows you to replace +Dex in AC calculation with +Str.
I don't super understand how it works myself, but reading the Monk and Barbarian's AC (with unarmoured defence) leads me to think that this might work:
`<stat name="ac:winters might" value="strength:modifier" />`
`<stat name="ac:calculation" value="ac:winters might" bonus="calculation" />`

**Comment by Rieleniel** [comment]
Been there, didn't work. Something else might be, I subtracted DEX and
added STR, but that doesn't work on heavy and medium armour because of the
limit. That is what I can't really fix.

Cold_Ankles <notifications@github.com> ezt írta (időpont: 2019. aug. 16.,
Pén 11:43):

**Comment by ColdAnkles** [comment]
Probably need @swdriessen then - I'm not super sure how the stat bonus stuff works.

**Comment by LordSionnach** [comment]
Hey, I'm alive! Getting back to this now, gonna start the Dream Cartography subclass.

**Comment by NickVendel** [comment]
@Rieleniel can you throw me your file, i wanna see how you did it

**Comment by swdriessen** [comment]
leaving this here for anyone who wants to make the familiars:
https://github.com/aurorabuilder/elements/blob/master/core/monster-manual/companions.xml
